### ISSUE TITLE
error: Justfile does not contain recipe `build`.

### ISSUE THREAD

**Issue by CypurrKitty** [michaelabon/streamdeck-logitech-litra-lights#10]
Getting:

```
$ just install build link
error: Justfile does not contain recipe `build`.
```

When running the 'just install build link` command

Any suggestions would be appreciated.

**Comment by michaelabon** [comment]
Hey @CypurrKitty. Thanks for checking it out. You've encouraged me to figure out how to build and release it on my own. Can you try to install [the pre-built version](https://github.com/michaelabon/streamdeck-logitech-litra-lights/releases/tag/v1.0.4) and let me know what works and what doesn't work for you?

## Installation instructions

1. Download the `.streamDeckPlugin` file from [the Releases page](https://github.com/michaelabon/streamdeck-logitech-litra-lights/releases/tag/v1.0.4).
2. In your Downloads folder, double-click that ca.michaelabon.logitech-litra-lights.streamDeckPlugin file. It should install in your Stream Deck application.
3. If it installs correctly, there will be a new section called Logitech Litra. It will have two actions: one to set your light(s) to a particular temperature and colour, one to turn your light(s) off.
    <img width="952" alt="Screenshot 2024-05-02 at 10 06 41" src="https://github.com/michaelabon/streamdeck-logitech-litra-lights/assets/567950/30de47e7-1a62-4b21-8183-fbacd736c2cf">

**Comment by michaelabon** [comment]
I found out that v1.0.4 won't actually run, in part because that was my first public release and I missed an important step. [Try out v1.0.5.0](https://github.com/michaelabon/streamdeck-logitech-litra-lights/releases/tag/v1.0.5.0) which I've confirmed works with my own setup. 

Again, I'm eager for feedback. Let me know here or in a new issue if you have any questions or problems.

**Comment by 8ternity** [comment]
Does the newer version we need to compile it or it's working right away like you mention in the reply here "https://github.com/michaelabon/streamdeck-logitech-litra-lights/issues/10#issuecomment-2091088920" ?

Because yes the app is located into Stream Deck plugins but gives error when pressing buttons 👍 
![2024-11-13_18h46_53](https://github.com/user-attachments/assets/986e052f-ec32-4c5a-92c3-78b91adcdea7)
